openapi: 3.0.3

info:
  title: REST API TEMPLATE
  version: 1.0.0
  description: Lifebit platform REST API template
servers:
  - url: http://localhost:3000
    description: REST API TEMPLATE
paths:
  /clinical-portal/v1/access-control/user-roles:
    $ref: './access-control/userRoles.yaml'
  /clinical-portal/v1/access-control/roles/me:
    $ref: './access-control/me.yaml'
  /clinical-portal/v1/access-control/invited-role:
    $ref: './access-control/invitedRole.yaml'
  /clinical-portal/v1/access-control/roles:
    $ref: './access-control/roles.yaml'
  /clinical-portal/v1/health:
    $ref: './health.yaml'
  /clinical-portal/v1/individual-browser/workgroup:
    $ref: './individual-browser/workgroup.yaml'
  /clinical-portal/v1/individual-browser/workgroup/{id}:
    $ref: './individual-browser/workgroupById.yaml'
