openapi: 3.0.3

info:
  title: Clinical portal rest api
  version: 1.0.0
  description: Clinical portal rest api
servers:
  - url: http://localhost:3000
    description: Clinical portal backend
paths:
  /clinical-portal/v1/access-control/user-roles:
    $ref: './access-control/userRoles.yaml'
  /clinical-portal/v1/access-control/roles/me:
    $ref: './access-control/me.yaml'
  /clinical-portal/v1/access-control/invited-role:
    $ref: './access-control/invitedRole.yaml'
  /clinical-portal/v1/access-control/roles:
    $ref: './access-control/roles.yaml'
  /clinical-portal/v1/health:
    $ref: './health.yaml'
  /clinical-portal/v1/individual-browser/workgroup:
    $ref: './individual-browser/workgroup/workgroup.yaml'
  /clinical-portal/v1/individual-browser/workgroup/{id}:
    $ref: './individual-browser/workgroup/workgroupById.yaml'
  /clinical-portal/v1/individual-browser/workgroup/search:
    $ref: './individual-browser/workgroup/workgroupSearch.yaml'
  /clinical-portal/v1/individual-browser/workgroup/patient:
    $ref: './individual-browser/workgroup/workgroupPatient.yaml'
  /clinical-portal/v1/individual-browser/workgroup/suggestions:
    $ref: './individual-browser/workgroup/workgroupSuggestions.yaml'
  /clinical-portal/v1/individual-browser/workgroup/{id}/patient/{pId}:
    $ref: './individual-browser/workgroup/workgroupPatientById.yaml'
  /clinical-portal/v1/individual-browser/workgroup/{id}/patient/{pId}/save-marker:
    $ref: './individual-browser/workgroup/workgroupPatientByIdSaveMarker.yaml'
  /clinical-portal/v1/individual-browser/workgroup/{id}/patients:
    $ref: './individual-browser/workgroup/patientByWorkgroupId.yaml'
  /clinical-portal/v1/individual-browser/workgroup/{id}/patient/{pId}/field:
    $ref: './individual-browser/workgroup/workgroupPatientField.yaml'
  /clinical-portal/v1/individual-browser/workgroup/{id}/patient/{pId}/field/{fieldId}:
    $ref: './individual-browser/workgroup/workgroupPatientFieldByFieldId.yaml'
  /clinical-portal/v1/individual-browser/workgroup/patient/validate:
    $ref: './individual-browser/workgroup/workgroupPatientValidate.yaml'
  /clinical-portal/v1/individual-browser/comparison/field/{id}/variant/{variant}:
    $ref: './individual-browser/comparison/getComparisonByFieldAndVariant.yaml'
  /clinical-portal/v1/individual-browser/comparison/variant/{variant}/participants:
    $ref: './individual-browser/comparison/getComparisonParticipantsByVariant.yaml'
  /clinical-portal/v1/individual-browser/comparison/workgroup/{id}/patients/{pId}/field:
    $ref: './individual-browser/comparison/addComparisonFilterToPatient.yaml'
  /clinical-portal/v1/individual-browser/comparison/gene/{gene}/participants:
    $ref: './individual-browser/comparison/getComparisonParticipantsByGene.yaml'
  /clinical-portal/v1/individual-browser/comparison/field/{id}/gene/{gene}:
    $ref: './individual-browser/comparison/getComparisonByFieldAndGene.yaml'
  /clinical-portal/v1/individual-browser/comparison/workgroup/{id}/patients/{pId}/field/{fieldId}:
    $ref: './individual-browser/comparison/removeComparisonFilterFromPatient.yaml'
  /clinical-portal/v1/individual-browser/comparison/variant/{variant}/graph:
    $ref: './individual-browser/comparison/getComparisonGraphDataByVariant.yaml'
