name: code-coverage-workflow
on:
  schedule:
    # Runs every Satarday at 00:00
    # https://docs.github.com/en/free-pro-team@latest/actions/reference/events-that-trigger-workflows#scheduled-events
    - cron: '0 0 * * 6'
jobs:
  release:
    name: Generate badges code-coverage
    runs-on: ubuntu-latest
    container: node:16.4.0-buster
    steps:
      - name: Mirror action step
        id: mirror
        uses: google/mirror-branch-action@v1.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          source: 'main'
          dest: 'hkgi-staging'
      - uses: actions/checkout@v2
        with:
          ref: 'code-coverage'
          fetch-depth: 0
      - name: Install dependencies
        run: npm i
      - name: Generate Badges
        run: |
          chmod -R 777 ./badges
          git config user.name github-actions
          git config user.email github-actions@github.com
          npm run test:badges
          git add ./badges
          git commit -m "Automated code-coverage"
          git push
      - uses: repo-sync/pull-request@v2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          source_branch: 'code-coverage'
          destination_branch: 'main'
          pr_title: '[Automated] Merge code-coverage into main'
          pr_body: 'Pull request create by release Github Action.'
          pr_label: 'team: data'
