name: HKGI Staging to Production Release
on:
  workflow_dispatch:
jobs:
  mirror_job:
    runs-on: ubuntu-latest
    name: Mirror hkgi-staging branch to hkgi-production branch
    steps:
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"
      - name: Checkout hkgi-staging Branch
        uses: actions/checkout@v2
        with:
          ref: 'hkgi-staging'
      - name: Create Old production Release
        id: oldsnapshot
        uses: actions/create-release@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.date.outputs.date }}-hkgi-production
          release_name: ${{ steps.date.outputs.date }}-hkgi-production
          commitish: hkgi-production
          draft: false
          prerelease: false
      - name: Create Release
        id: snapshot
        uses: actions/create-release@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.date.outputs.date }}-hkgi-staging
          release_name: ${{ steps.date.outputs.date }}-hkgi-staging
          commitish: hkgi-staging
          draft: false
          prerelease: false
      - name: Mirror action step
        id: mirror
        uses: google/mirror-branch-action@v1.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          source: 'hkgi-staging'
          dest: 'hkgi-production'
